stages:
  merge:
    cmd: python src/data/merge.py
    deps:
      - data/raw/GDSC2-dataset.csv
      - data/raw/Cell_Lines_Details.xlsx
      - src/data/merge.py
    outs:
      - data/processed/merged_data.csv

  train:
    cmd: python src/models/train.py
    deps:
      - data/processed/merged_data.csv
      - src/models/train.py
    params:
      - train.model_type
      - train.max_depth
      - train.n_estimators
      - train.learning_rate
      - train.subsample
      - train.colsample_bytree
      - train.random_state
    outs:
      - models/best_model_XGBoost_(Tuned).pkl
      - models/scaler.pkl
